// ===============================================================
// MONEY SETTLEMENT DUPLICATE OVERRIDE LOG MODEL
// ===============================================================
const logger = require("../../api/logger");

module.exports = (sequelize, DataTypes) => {
  const MoneySettlementOverrideLog = sequelize.define('MoneySettlementOverrideLog', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    settlementId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: 'Reference to the created/updated MoneySettlement record'
    },
    matchedSettlementIds: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Array of existing duplicate MoneySettlement IDs that were matched'
    },
    amount: {
      type: DataTypes.DECIMAL(20, 2),
      allowNull: false,
      comment: 'Amount of the settlement'
    },
    currencyId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: 'Currency ID'
    },
    ministryId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      comment: 'Ministry ID'
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      comment: 'User ID who confirmed/overrode the duplicate warning'
    },
    overrideReason: {
      type: DataTypes.STRING(255),
      allowNull: true,
      comment: 'Reason provided for overriding the duplicate'
    },
    overrideMessage: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'Detailed override message generated by system'
    },
    ipAddress: {
      type: DataTypes.STRING(45),
      allowNull: true,
      comment: 'IP address of client'
    },
    userAgent: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'User agent info'
    }
  }, {
    sequelize,
    tableName: 'MoneySettlementOverrideLog',
    timestamps: true,
    createdAt: true,
    updatedAt: 'updateTimestamp',
    freezeTableName: true,
    indexes: [
      {
        fields: ['settlementId'],
        name: 'idx_ms_override_settlement_id'
      },
      {
        fields: ['userId'],
        name: 'idx_ms_override_user_id'
      },
      {
        fields: ['ministryId'],
        name: 'idx_ms_override_ministry_id'
      },
      {
        fields: ['currencyId'],
        name: 'idx_ms_override_currency_id'
      }
    ]
  });

  MoneySettlementOverrideLog.associate = models => {
    logger.info(`Associating table MoneySettlementOverrideLog with models`);
    MoneySettlementOverrideLog.belongsTo(models.moneySettlement, {
      foreignKey: 'settlementId',
      as: 'settlement',
    });
    MoneySettlementOverrideLog.belongsTo(models.user, {
      foreignKey: 'userId',
      as: 'user',
    });
    MoneySettlementOverrideLog.belongsTo(models.currency, {
      foreignKey: 'currencyId',
      as: 'currency',
    });
    MoneySettlementOverrideLog.belongsTo(models.ministry, {
      foreignKey: 'ministryId',
      as: 'ministry',
    });
  };

  return MoneySettlementOverrideLog;
};
