// ===============================================================
// MONEY ADVANCE DUPLICATE OVERRIDE LOG MODEL
// ===============================================================
const logger = require("../../api/logger");

module.exports = (sequelize, DataTypes) => {
  const MoneyAdvanceOverrideLog = sequelize.define('MoneyAdvanceOverrideLog', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    moneyAdvanceId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: 'Reference to the created/updated MoneyAdvance record'
    },
    matchedAdvanceIds: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: 'Array of existing duplicate MoneyAdvance IDs that were matched'
    },
    amount: {
      type: DataTypes.DECIMAL(20, 2),
      allowNull: false,
      comment: 'Amount of the advance'
    },
    currencyId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: 'Currency ID'
    },
    ministryId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      comment: 'Ministry ID'
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      comment: 'User ID who confirmed/overrode the duplicate warning'
    },
    overrideReason: {
      type: DataTypes.STRING(255),
      allowNull: true,
      comment: 'Reason provided for overriding the duplicate'
    },
    overrideMessage: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'Detailed override message generated by system'
    },
    ipAddress: {
      type: DataTypes.STRING(45),
      allowNull: true,
      comment: 'IP address of client'
    },
    userAgent: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'User agent info'
    }
  }, {
    sequelize,
    tableName: 'MoneyAdvanceOverrideLog',
    timestamps: true,
    createdAt: true,
    updatedAt: 'updateTimestamp',
    freezeTableName: true,
    indexes: [
      {
        fields: ['moneyAdvanceId'],
        name: 'idx_ma_override_money_advance_id'
      },
      {
        fields: ['userId'],
        name: 'idx_ma_override_user_id'
      },
      {
        fields: ['ministryId'],
        name: 'idx_ma_override_ministry_id'
      },
      {
        fields: ['currencyId'],
        name: 'idx_ma_override_currency_id'
      }
    ]
  });

  MoneyAdvanceOverrideLog.associate = models => {
    logger.info(`Associating table MoneyAdvanceOverrideLog with models`);
    MoneyAdvanceOverrideLog.belongsTo(models.moneyAdvance, {
      foreignKey: 'moneyAdvanceId',
      as: 'moneyAdvance',
    });
    MoneyAdvanceOverrideLog.belongsTo(models.user, {
      foreignKey: 'userId',
      as: 'user',
    });
    MoneyAdvanceOverrideLog.belongsTo(models.currency, {
      foreignKey: 'currencyId',
      as: 'currency',
    });
    MoneyAdvanceOverrideLog.belongsTo(models.ministry, {
      foreignKey: 'ministryId',
      as: 'ministry',
    });
  };

  return MoneyAdvanceOverrideLog;
};
